### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by sporto** [ryannhg/date-format#11]
This is great package, thanks for making it.

Please add a CHANGELOG, this is very useful when trying to upgrade, specially when functions are removed or renamed.

Thanks

**Comment by ryan-haskell** [comment]
Hey @sporto ,

Sure thing! I've added in a CHANGELOG here:
https://github.com/ryannhg/date-format/blob/master/CHANGELOG.md

Thanks!
Ryan
