### ISSUE TITLE
Problem in timezone

### ISSUE THREAD

**Issue by gabriela-sartori** [ryannhg/date-format#12]
Hello.

First of all, thanks for this package. 
Today I was having a problem with the posix from 2018/10/04 being converted to 2018/01/04. Then I updated to 2.0.1 and everything was ok. Then I decided to not use Time.utc and use my local timezone (-3) using Time.here, and the format function seems to always use Time.utc, even if I pass my local time zone.

Would you mind checking if the function is correct?
Thanks!

**Comment by mgold** [comment]
[Looks correct](https://github.com/ryannhg/date-format/blob/f2e0134894fde94a3f1b46c3141629f9b07f2886/src/DateFormat.elm#L562) to me?

**Comment by ryan-haskell** [comment]
@G4BB3R I've closed the issue, let me know if you have any more concerns!

Thanks!
