### ISSUE TITLE
Version for 0.18

### ISSUE THREAD

**Issue by simonh1000** [ryannhg/date-format#17]
Would be great to have a version for 0.18, so that I can update my code dealing with dates/times before making the big switch for the code as a whole

**Comment by ryan-haskell** [comment]
Hey Simon!

There is a version out for 0.18 called [`ryannhg/elm-date-format`](https://github.com/ryannhg/elm-date-format), however it is deprecated and I won't be adding any additional features.

Happy date formatting!
Ryan

**Comment by simonh1000** [comment]
Thanks - sorry for my poor searching beforehand
Note that there is a typo in the readme

```
elm package install ryannhg/elm-date-format
elm-package install ryannhg/elm-date-format
```
