### ISSUE TITLE
Localized formatting

### ISSUE THREAD

**Issue by mgold** [ryannhg/date-format#2]
There should be a way to localize formatting for dates. 

A few people have submitted PRs to my formatting library over the years. (I don't plan to update it to 0.19 - your token approach is better.) The results are [here](https://github.com/mgold/elm-date-format/blob/master/src/Date/Local.elm). You don't necessarily have to add all the localizations, but having a way for others to do them is useful. I think you hit upon a good pattern with the record of functions in the Relative module.

**Comment by ryan-haskell** [comment]
Hey Max,

I really like that idea!

It would be pretty silly to only support the english strings I've defined.

Let me update my `DateFormat` module!

Thanks,
Ryan

**Comment by mgold** [comment]
Awesome!

I literally had someone add a [PR for Greek](https://github.com/mgold/elm-date-format/pull/27) today.

**Comment by ryan-haskell** [comment]
Hey Max!

Just pushed up a 1.1.0 release to elm-package.

Check out this example if you want to see how it works:
https://github.com/ryannhg/date-format/blob/master/examples/FormatWithOptions.elm

Thanks for your suggestion, it greatly improved the overall flexibility of the package!

Thanks again,
Ryan
