### ISSUE TITLE
Three letter day name formatting? (e.g. Sun, Mon etc)

### ISSUE THREAD

**Issue by samsondav** [ryannhg/date-format#24]
Hi there, thanks for this awesome library!

I'm trying to get the name of the day in three letter format (Sun, Mon, Tue) etc. How can I do this with the library?

**Comment by mgold** [comment]
Does `dayOfWeekNameAbbreviated` not work?

**Comment by samsondav** [comment]
Yes it does! The documentation wrongly lists the output as having only two letters. Thanks!
