### ISSUE TITLE
Expose DateFormat.defaultOptions

### ISSUE THREAD

**Issue by okkero** [ryannhg/date-format#6]
If I am writing a translation library, it would be nice to be able to work with DateFormat in a generic way. `DateFormat.defaultOptions` is a good default for the English format. However, the only way to use it is to use `DateFormat.format` instead of `DateFormat.formatWithOptions`. I would need to use DateFormat.formatWithOptions for every other language, though. So English becomes this weird special case.

So right now I either have to define my own English `DateFormat.FormatOptions` and use it with `DateFormat.formatWithOptions`, or I have to handle English as a special case and call `DateFormat.format` when formatting dates in English.

It would be nice to have `DateFormat.defaultOptions` exposed.

**Comment by ryan-haskell** [comment]
Hey @okkero,

That makes sense. I'm going to make a big API update to support multiple languages.

There's more information about those changes [this pull request](https://github.com/ryannhg/date-format/pull/5#issuecomment-418402107).

I'll be sure to post updates in this issue, so it's easy to follow.

Thanks!
Ryan

**Comment by ryan-haskell** [comment]
Hey @okkero ,

I just pushed the updated API to the `master` branch if you want to check it out.

Added in a `DateFormat.Language` module that exposes the languages `english` and `spanish` for now.

Does this API update address your concerns?

Let me know!
Ryan

**Comment by okkero** [comment]
@ryannhg Yes, from what I can see it seems to address my concerns and more. Thank you for this :)

**Comment by ryan-haskell** [comment]
Awesome, feel free to grab `2.0.0` whenever you get a chance!
https://package.elm-lang.org/packages/ryannhg/date-format/latest/

And come back here if you have any other good suggestions 😄 

Thanks again!
Ryan
